ALTER TABLE "AdminUser" ADD COLUMN IF NOT EXISTS "gender" TEXT;
ALTER TABLE "AdminUser" ADD COLUMN IF NOT EXISTS "profileImage" TEXT;

ALTER TABLE "SuperAdminUser" ADD COLUMN IF NOT EXISTS "gender" TEXT;
ALTER TABLE "SuperAdminUser" ADD COLUMN IF NOT EXISTS "profileImage" TEXT;
