from typing import Dict

from crewai import Agent, LLM


def build_agents(toolset: Dict[str, object], llm: LLM) -> Dict[str, Agent]:
    return {
        "market": Agent(
            role="Market Data Specialist",
            goal="Provide clean historical market data and indicators for forecasting.",
            backstory="Expert in financial data sourcing and normalization.",
            tools=[toolset["market"]],
            llm=llm,
            allow_delegation=False,
            max_iter=1,
            max_retry_limit=1,
            verbose=False,
        ),
        "news": Agent(
            role="News Fetcher",
            goal="Collect relevant market news for the requested stock symbol.",
            backstory="Specializes in filtering market-relevant headlines from trusted sources.",
            tools=[toolset["news"]],
            llm=llm,
            allow_delegation=False,
            max_iter=1,
            max_retry_limit=1,
            verbose=False,
        ),
        "sentiment": Agent(
            role="Sentiment Analyst",
            goal="Analyze sentiment of recent stock-related news articles.",
            backstory="Uses VADER sentiment analysis to classify market sentiment.",
            tools=[toolset["sentiment"]],
            llm=llm,
            allow_delegation=False,
            max_iter=1,
            max_retry_limit=1,
            verbose=False,
        ),
        "preprocess": Agent(
            role="Data Preprocessor",
            goal="Merge market and sentiment data, then prepare Prophet-ready inputs.",
            backstory="Ensures datasets are clean, aligned, and ready for forecasting.",
            tools=[toolset["merge"], toolset["prophet"]],
            llm=llm,
            allow_delegation=False,
            max_iter=1,
            max_retry_limit=1,
            verbose=False,
        ),
        "predict": Agent(
            role="Forecasting Specialist",
            goal="Generate reliable price forecasts using Prophet or fallback models.",
            backstory="Focuses on robust and explainable time-series forecasting.",
            tools=[toolset["predict"]],
            llm=llm,
            allow_delegation=False,
            max_iter=1,
            max_retry_limit=1,
            verbose=False,
        ),
        "insight": Agent(
            role="Market Insight Analyst",
            goal="Produce human-readable insights based on forecast outputs.",
            backstory="Summarizes quantitative predictions into concise insights.",
            tools=[toolset["insight"]],
            llm=llm,
            allow_delegation=False,
            max_iter=1,
            max_retry_limit=1,
            verbose=False,
        ),
        "report": Agent(
            role="Report Generator",
            goal="Generate a structured prediction report for storage and auditing.",
            backstory="Creates standardized JSON reports from forecast outputs.",
            tools=[toolset["report"]],
            llm=llm,
            allow_delegation=False,
            max_iter=1,
            max_retry_limit=1,
            verbose=False,
        ),
    }
